import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { education } from '../../data/education';
import { useI18n } from '../../i18n/useI18n';
import { resolveText } from '../../types';
import { Icon } from '../ui/Icon';
import { Button, Tag } from '../ui/Primitives';
import { useWindowManager } from '../../context/WindowManagerProvider';
export function EducationApp() {
    const { t, locale } = useI18n();
    const { openWindow } = useWindowManager();
    return (_jsx("div", { className: "scroll-thin h-full overflow-y-auto px-4 py-5 sm:px-6 sm:py-6", children: _jsxs("div", { className: "mx-auto flex max-w-3xl flex-col gap-6", children: [_jsxs("header", { children: [_jsx("h3", { className: "text-lg font-semibold tracking-tight text-ink", children: t.education.title }), _jsx("p", { className: "mt-0.5 text-xs text-muted", children: t.education.subtitle })] }), _jsx("ol", { className: "flex flex-col gap-4", children: education.map((entry, index) => (_jsx("li", { className: "animate-rise-in", style: { animationDelay: `${index * 70}ms` }, children: _jsxs("article", { className: "card-surface relative overflow-hidden p-5", children: [_jsx("span", { "aria-hidden": "true", className: "absolute inset-y-0 left-0 w-1 bg-gradient-to-b from-accent to-transparent" }), _jsxs("div", { className: "flex flex-wrap items-start justify-between gap-x-4 gap-y-1", children: [_jsx("h4", { className: "max-w-xl text-[15px] font-semibold leading-snug text-ink", children: resolveText(entry.degree, locale) }), _jsx("p", { className: "font-mono text-xs text-secondary", children: entry.period })] }), entry.degreeAlt ? (_jsx("p", { className: "mt-1.5 text-xs leading-relaxed text-muted", children: resolveText(entry.degreeAlt, locale) })) : null, _jsxs("div", { className: "mt-3 flex flex-wrap items-center gap-2", children: [_jsxs("span", { className: "inline-flex items-center gap-1.5 rounded-lg border border-[var(--border)] bg-[var(--hover-surface)] px-2.5 py-1 text-[13px] font-medium text-ink", children: [_jsx(Icon, { name: "school", size: 15, className: "text-accent" }), entry.school] }), entry.note ? _jsx(Tag, { tone: "accent", children: resolveText(entry.note, locale) }) : null] }), entry.schoolDetail ? (_jsx("p", { className: "mt-2 text-[11px] leading-relaxed text-muted", children: resolveText(entry.schoolDetail, locale) })) : null] }) }, entry.id))) }), _jsxs("div", { className: "rounded-xl border border-dashed border-[var(--border)] px-4 py-4", children: [_jsx("p", { className: "text-[13px] leading-relaxed text-secondary", children: t.certs.subtitle }), _jsx(Button, { size: "sm", variant: "secondary", className: "mt-3", icon: _jsx(Icon, { name: "award", size: 14 }), onClick: () => openWindow('certifications'), children: t.apps.certifications })] })] }) }));
}
