import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cvDocuments } from '../../data/resume';
/**
 * The CV rendered as a document inside the Resume window.
 * Mirrors the print stylesheet in `cvPrint.ts` so what is on screen matches
 * what the browser produces as PDF.
 */
export function CvDocument({ locale }) {
    const cv = cvDocuments[locale === 'fr' ? 'fr' : 'en'];
    return (_jsxs("article", { className: "mx-auto max-w-[210mm] bg-white px-6 py-7 text-[#14171f] shadow-[var(--shadow-soft)] sm:px-9 sm:py-9", children: [_jsxs("header", { className: "text-center", children: [_jsx("h2", { className: "text-[22px] font-bold uppercase tracking-[0.1em] text-[#14171f]", children: cv.name }), _jsx("p", { className: "mt-1 text-[13px] font-semibold text-[#14171f]", children: cv.title }), _jsx("p", { className: "mt-1 text-[12px] text-[#4b5563]", children: cv.contactLine }), _jsx("p", { className: "mt-1.5 flex flex-wrap justify-center gap-x-2 text-[11px]", children: cv.links.map((link, index) => (_jsxs("span", { className: "flex items-center gap-2", children: [index > 0 ? _jsx("span", { className: "text-[#9ca3af]", children: "|" }) : null, _jsxs("a", { href: link.url, target: "_blank", rel: "noreferrer noopener", className: "text-[#1a4fd6] hover:underline", children: [link.label, ": ", link.display] })] }, link.url))) })] }), cv.sections.map((section) => (_jsxs("section", { className: "mt-4", children: [_jsx("h3", { className: "border-b border-[#14171f] pb-0.5 text-[11px] font-bold uppercase tracking-[0.08em] text-[#14171f]", children: section.heading }), section.intro || section.line ? (_jsx("p", { className: "mt-1.5 text-justify text-[12px] leading-[1.45] text-[#14171f]", children: section.intro ?? section.line })) : (_jsx("div", { className: "mt-1.5 flex flex-col gap-2", children: section.entries?.map((entry) => (_jsxs("div", { className: "break-inside-avoid", children: [_jsxs("div", { className: "flex flex-wrap items-baseline justify-between gap-x-3", children: [_jsx("strong", { className: "text-[12.5px] font-semibold text-[#14171f]", children: entry.title }), entry.period ? (_jsx("span", { className: "font-mono text-[10.5px] text-[#4b5563]", children: entry.period })) : null] }), entry.subtitle ? (_jsx("p", { className: "mt-0.5 text-[11.5px] italic text-[#4b5563]", children: entry.subtitle })) : null, entry.body ? (_jsx("p", { className: "mt-0.5 text-[11.5px] italic text-[#4b5563]", children: entry.body })) : null, entry.bullets?.length ? (_jsx("ul", { className: "mt-1 flex list-disc flex-col gap-0.5 pl-4 text-[11.5px] leading-[1.4] text-[#14171f]", children: entry.bullets.map((bullet) => (_jsx("li", { children: bullet }, bullet))) })) : null] }, entry.title))) }))] }, section.id)))] }));
}
